version: '3.7'
services:
  master:
    image: 'redis:5.0.9'
    container_name: 'redis-master'
    restart: always
    command: redis-server --appendonly yes
    ports:
      - '6379:6379'
    networks:
      - redis-net
  salve1:
    image: 'redis:5.0.9'
    container_name: 'redis-salve1'
    restart: always
    command: redis-server --appendonly yes --slaveof redis-master 6379
    ports:
      - '6380:6379'
    networks:
      - redis-net
  salve2:
    image: 'redis:5.0.9'
    container_name: 'redis-salve2'
    restart: always
    command: redis-server --appendonly yes --slaveof redis-master 6379
    ports:
      - '6381:6379'
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge
