server:
  port: 9991

resilience4j:
  circuitbreaker:
    instances:
      checkRandom:
              registerHealthIndicator: true
              slidingWindowSize: 10
              permittedNumberOfCallsInHalfOpenState: 3
      #        slidingWindowType: TIME_BASED
              minimumNumberOfCalls: 5
              waitDurationInOpenState: 5s
              failureRateThreshold: 50
              eventConsumerBufferSize: 10
  #        recordFailurePredicate: io.github.robwin.exception.RecordFailurePredicate
  ratelimiter:
    instances:
      backendA:
        limitForPeriod: 2
        limitRefreshPeriod: 10s
        timeoutDuration: 0
        registerHealthIndicator: true
        eventConsumerBufferSize: 100
      backendB:
        limitForPeriod: 5
        limitRefreshPeriod: 10s
        timeoutDuration: 3s

  management:
    health:
      circuitbreakers:
        enabled: true
    endpoints:
      web:
        exposure:
          include:
            - '*'
    endpoint:
      health:
        show-details: always
